###                            ###
##  Intave Proxy Support 0.9.3  ##
##           by Jpx3            ##
###                            ###

# Connections
connection:

  # Connection between proxy and database.
  sql:

    enabled: false

    connection:
      jdbc-service: "mysql"
      host: "ich.bin.net"
      port: -1
      database: "tabledance24"
      user: "XxX$$R_I_C_H_Y$$XxX"
      password: "12345678"

    create-tables: true

  # Connection between our proxy and bukkit (where Intave is running).
  bukkit:

    enabled: true

punishment:

  # RUNTIME | Punishments are cleared after server restart and only available on this proxy
  # SQL | Punishments are saved in a database and cached
  # SQL-NC | Punishments are saved in a database and are not cached
  # NONE
  driver: "RUNTIME"

  # Message layout
  #
  # {expire-short} - Time until expiration (format-example: "13m 23d 13h 22m 19s" or "never")
  # {expire}       - Time until expiration with full annotations (format-example: "13 months, 23 days, 13 hours, 22 minutes & 19 seconds" or "never")
  # {reason}       - Entered reason for punishment
  message-layout:

    kick-layout: |
      &4&lYou have been kicked.&r&r

      &fReason: &b&l{reason}&r&r&r

      &r&cPlease contact our staff in case&r&r
      &cyou have any questions regarding this action.&r

    ban-layout: |
      &4&lYou have been banned.&r&r

      &fReason: &b&l{reason}&r&r&r
      &fExpires: &b&l{expire-short}&r&r&r

      &r&cPlease contact our staff in case&r&r
      &cyou have any questions regarding this action.&r

